# =============================================================
# mise.toml - Declarative Polyglot Runtime Toolchains
# Managed via mise (https://mise.jdx.dev)
# =============================================================

[tools]
java = "lts"
maven = "latest"
go = "latest"
python = "latest"
node = "lts"
terraform = "latest"
rust = "latest"
neovim = "latest"
eza = "latest"
bat = "latest"
glow = "latest"

[settings]
legacy_version_file = true
experimental = true
go.set_gobin = false
go.set_gopath = false
