" =============================================================
" Vim Configuration - windows-settings
" Ported from home-settings/.vimrc
" =============================================================

" Plugin management (Pathogen)
if filereadable(expand('~/vimfiles/autoload/pathogen.vim')) || filereadable(expand('~/.vim/autoload/pathogen.vim'))
    execute pathogen#infect()
    execute pathogen#helptags()
endif

" Suppress Python syntax/deprecation warnings
let $PYTHONWARNINGS = "ignore"

" UltiSnips snippet triggers
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"

" Auto-Pairs configuration (Brace matching and auto-closing)
let g:AutoPairsShortcutJump = '<c-l>'

" Indentation & Formatting
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set showmatch
set matchtime=2

" Syntax & Visual Theme
syntax enable
set background=dark
silent! colorscheme solarized

" Diff Highlight Formatting
highlight DiffAdd term=reverse cterm=bold ctermbg=green ctermfg=white 
highlight DiffChange term=reverse cterm=bold ctermbg=cyan ctermfg=black 
highlight DiffText term=reverse cterm=bold ctermbg=gray ctermfg=black 
highlight DiffDelete term=reverse cterm=bold ctermbg=red ctermfg=black

" Navigation
map <Home> ^
imap <Home> <Esc>^i
