" =============================================================
" Vim Configuration - windows-settings
" Ported from home-settings/.vimrc
" =============================================================

" Set runtimepath to include standard Unix and Windows locations
set runtimepath^=~/.vim,~/.vim/after,~/vimfiles,~/vimfiles/after

" Plugin management (Pathogen)
if filereadable(expand('~/.vim/autoload/pathogen.vim'))
    source ~/.vim/autoload/pathogen.vim
endif
if filereadable(expand('~/vimfiles/autoload/pathogen.vim'))
    source ~/vimfiles/autoload/pathogen.vim
endif

if exists('*pathogen#infect')
    execute pathogen#infect()
    execute pathogen#helptags()
endif

" Python 3 Configuration for UltiSnips on Windows
if has('win32') || has('win64')
    set pythonthreedll=python3.dll
endif

" Suppress Python syntax/deprecation warnings
let $PYTHONWARNINGS = "ignore"

" UltiSnips snippet triggers
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"

" Auto-Pairs configuration (Brace matching and auto-closing)
let g:AutoPairsShortcutJump = '<c-l>'

" Indentation & Formatting
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set showmatch
set matchtime=2

" Syntax & Visual Theme
syntax enable
set background=dark
silent! colorscheme solarized

" Diff Highlight Formatting
highlight DiffAdd term=reverse cterm=bold ctermbg=green ctermfg=white 
highlight DiffChange term=reverse cterm=bold ctermbg=cyan ctermfg=black 
highlight DiffText term=reverse cterm=bold ctermbg=gray ctermfg=black 
highlight DiffDelete term=reverse cterm=bold ctermbg=red ctermfg=black

" Navigation
map <Home> ^
imap <Home> <Esc>^i
